name: 'Python Tests'
description: 'Run pytest with coverage'
author: 'provide.io llc'

inputs:
  test-directory:
    description: 'Test directory'
    required: false
    default: 'tests/'
  coverage-threshold:
    description: 'Coverage threshold percentage'
    required: false
    default: '80'
  parallel:
    description: 'Run tests in parallel'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 📥 Checkout ci-tooling
      uses: actions/checkout@v4
      with:
        repository: provide-io/ci-tooling
        ref: main
        path: .ci-tooling

    - name: 🧪 Run Tests
      shell: bash
      run: |
        source ./workenv/bin/activate
        .ci-tooling/scripts/test/run-pytest.sh "${{ inputs.test-directory }}" ${{ inputs.coverage-threshold }} ${{ inputs.parallel }}

branding:
  icon: 'check-square'
  color: 'blue'
